#!/bin/bash
#
# Run script for initial sampling case: mass_constant_sampled
# Platform: matrix
# Generated by run_erf.sh on Thu Jan 29 16:26:33 PST 2026
#

set -e

# Configuration
NTASKS=4
NNODES=1
GPU_SUPPORT=true
GPUS_PER_TASK=1
EXEC=/g/g92/ghosh5/Codes/ERF-builds/matrix/Exec/MoistRegTests/Bubble/erf_bubble
INPUT=inputs_mass_constant_sampled

echo "Running ERF for initial sampling (max_step = 0)"
echo "Case: mass_constant_sampled"
echo "Platform: matrix"
echo "Tasks: $NTASKS"
echo "Nodes: $NNODES"
[[ "$GPU_SUPPORT" == "true" ]] && echo "GPUs per task: $GPUS_PER_TASK"
echo

# Determine how to launch MPI job based on scheduler
# SLURM-based system (using debug queue for interactive runs)
DEBUG_QUEUE=pdebug
if [[ "$GPU_SUPPORT" == "true" ]]; then
    # Total GPUs = ntasks * gpus_per_task
    TOTAL_GPUS=$(($NTASKS * $GPUS_PER_TASK))
    srun -n $NTASKS -N $NNODES -p $DEBUG_QUEUE -G $TOTAL_GPUS $EXEC $INPUT 2>&1 | tee output.log
else
    srun -n $NTASKS -N $NNODES -p $DEBUG_QUEUE $EXEC $INPUT 2>&1 | tee output.log
fi

echo
echo "Initial sampling complete. Check output files."
