#!/bin/bash
#
# Run script for initial sampling case: radius_log_normal
# Platform: tuolumne
# Generated by run_erf.sh on Thu Jan 29 16:25:53 PST 2026
#

set -e

# Configuration
NTASKS=4
NNODES=1
GPU_SUPPORT=true
GPUS_PER_TASK=1
EXEC=/g/g92/ghosh5/Codes/ERF-builds/tuolumne/Exec/erf_exec
INPUT=inputs_radius_log_normal

echo "Running ERF for initial sampling (max_step = 0)"
echo "Case: radius_log_normal"
echo "Platform: tuolumne"
echo "Tasks: $NTASKS"
echo "Nodes: $NNODES"
[[ "$GPU_SUPPORT" == "true" ]] && echo "GPUs per task: $GPUS_PER_TASK"
echo

# Determine how to launch MPI job based on scheduler
# Flux-based system (using debug queue for interactive runs)
DEBUG_QUEUE=pdebug
flux run --exclusive --nodes=$NNODES --ntasks $NTASKS -q=$DEBUG_QUEUE $EXEC $INPUT 2>&1 | tee output.log

echo
echo "Initial sampling complete. Check output files."
