# Override: SuperDroplets with dual aerosols (NaCl + soil)
# Mixed aerosol population

# Moisture model
erf.moisture_model  = "SuperDroplets"

# Plot variables with accumulation for both species
erf.plot_vars_1     = density rhotheta rhoQ1 rhoQ2 rhoadv_0 x_velocity y_velocity z_velocity pressure theta scalar temp pres_hse dens_hse pert_pres pert_dens eq_pot_temp qt qv qc qrain rain_accum super_droplets_moisture_number_density super_droplets_moisture_mass_density accum_NaCl accum_soil
particles.disable_plt = true

# SDM parameters - dual aerosol species
super_droplets_moisture.initial_distribution_type = "uniform"
super_droplets_moisture.diagnostics_interval = 100
super_droplets_moisture.coalescence_kernel = "Halls"
super_droplets_moisture.aerosols = NaCl soil
super_droplets_moisture.initial_aerosol_distribution_type_NaCl = "mass_exponential"
super_droplets_moisture.initial_aerosol_min_mass_NaCl = 1.0e-22 #kg
super_droplets_moisture.initial_aerosol_mean_mass_NaCl = 1.0e-19 #kg
super_droplets_moisture.initial_aerosol_max_mass_NaCl = 1.0e-18 #kg
super_droplets_moisture.initial_aerosol_distribution_type_soil = "mass_exponential"
super_droplets_moisture.initial_aerosol_min_mass_soil = 1.0e-15 #kg
super_droplets_moisture.initial_aerosol_mean_mass_soil = 2.0e-12 #kg
super_droplets_moisture.initial_aerosol_max_mass_soil = 2.0e-13 #kg
super_droplets_moisture.initial_number_density = 1.0e7 #m^{-3}
super_droplets_moisture.initial_particles_per_cell = 256
