# Override: SuperDroplets with Ammonium Sulfate aerosol
# Lagrangian particle-based cloud microphysics

# Moisture model
erf.moisture_model  = "SuperDroplets"

# Additional plot variables for SDM
erf.plot_vars_1     = density rhotheta rhoQ1 rhoQ2 rhoadv_0 x_velocity y_velocity z_velocity pressure theta scalar temp pres_hse dens_hse pert_pres pert_dens eq_pot_temp qt qv qc qrain rain_accum super_droplets_moisture_number_density super_droplets_moisture_mass_density

# SDM parameters
super_droplets_moisture.initial_distribution_type = "uniform"
super_droplets_moisture.diagnostics_interval = 100
super_droplets_moisture.coalescence_kernel = "Halls"
super_droplets_moisture.multiplicity_type = "constant"
super_droplets_moisture.recycle_particles = false
super_droplets_moisture.aerosols = NH42SO4
super_droplets_moisture.initial_aerosol_distribution_type_NH42SO4 = "mass_exponential"
super_droplets_moisture.initial_aerosol_min_mass_NH42SO4 = 1.0e-22 #kg
super_droplets_moisture.initial_aerosol_mean_mass_NH42SO4 = 1.0e-20 #kg
super_droplets_moisture.initial_aerosol_max_mass_NH42SO4 = 2.0e-19 #kg
super_droplets_moisture.initial_number_density = 0.9e7 #m^{-3}
super_droplets_moisture.initial_particles_per_cell = 256
