# Override: c2_ppb_2_17 parameter set for various kernels
# Parameter set for 2^17 (131072) multiplicity with 1800s simulation time

# Time settings
stop_time = 1800.0

# Super Droplets specific parameters
super_droplets_moisture.diagnostics_interval = 12000
super_droplets_moisture.multiplicity_type = "constant"
super_droplets_moisture.initial_aerosol_distribution_type_NaCl = "mass_constant"
super_droplets_moisture.initial_aerosol_mean_mass_NaCl = 1.0e-22 #kg
super_droplets_moisture.initial_species_distribution_type_H2O = "mass_exponential"
super_droplets_moisture.initial_species_mean_mass_H2O = 1.19209728e-10 # kg
super_droplets_moisture.initial_number_density = 8.388608e6 #m^{-3}
super_droplets_moisture.initial_particles_per_cell = 2048