# Override: SuperDroplets with sedimentation coalescence kernel
# Lagrangian particle-based cloud microphysics

super_droplets_moisture.include_phase_change = false
super_droplets_moisture.advect_with_flow = false
super_droplets_moisture.advect_with_gravity = false
super_droplets_moisture.include_coalescence = true
super_droplets_moisture.coalescence_kernel = "sedimentation"
super_droplets_moisture.include_brownian_coalescence = false
super_droplets_moisture.coalescence_bin_size = 4 4 4