stop_time = 86400

geometry.prob_extent =  12800     12800    4000
amr.n_cell           =    128       128     100

erf.most.zref   = 20.0

erf.most.rico.theta_z0 = 300.0
erf.most.rico.qsat_z0 = 0.022

erf.fixed_dt           = 0.3
erf.fixed_mri_dt_ratio = 4

erf.check_int       = 2000

erf.plot_int_1      = 2000
erf.plot_vars_1     = density rhotheta x_velocity y_velocity z_velocity pressure temp theta qt qp qv qc qsat qrain rain_accum rel_humidity super_droplets_moisture_number_density

erf.dycore_horiz_adv_type    = Upwind_3rd
erf.dycore_vert_adv_type     = Upwind_3rd
erf.dryscal_horiz_adv_type   = Upwind_3rd
erf.dryscal_vert_adv_type    = Upwind_3rd
erf.moistscal_horiz_adv_type = Upwind_3rd
erf.moistscal_vert_adv_type  = Upwind_3rd

erf.buoyancy_type   = 1

super_droplets_moisture.initial_distribution_type = "uniform"
super_droplets_moisture.diagnostics_interval = 100
super_droplets_moisture.coalescence_kernel = "Halls"
super_droplets_moisture.aerosols = NH4HSO4
super_droplets_moisture.num_initializations = 2
super_droplets_moisture.density_scaling = true

super_droplets_moisture.0.initial_aerosol_distribution_type_NH4HSO4 = "radius_log_normal"
super_droplets_moisture.0.initial_aerosol_mean_radius_NH4HSO4 = 30.0e-9
super_droplets_moisture.0.initial_aerosol_std_radius_NH4HSO4 = 0.2468600779315258
super_droplets_moisture.0.initial_number_density = 9.0e7
super_droplets_moisture.0.initial_particles_per_cell = 64

super_droplets_moisture.1.initial_aerosol_distribution_type_NH4HSO4 = "radius_log_normal"
super_droplets_moisture.1.initial_aerosol_mean_radius_NH4HSO4 = 140.0e-9
super_droplets_moisture.1.initial_aerosol_std_radius_NH4HSO4 = 0.5596157879354227
super_droplets_moisture.1.initial_number_density = 1.5e7
super_droplets_moisture.1.initial_particles_per_cell = 64

erf.Pr_t      = 0.33333333333333
erf.Sc_t      = 0.33333333333333

erf.custom_forcing_uses_primitive_vars = true
