stop_time = 129600

geometry.prob_extent =  100000.  100000.  21000.
amr.n_cell           =    200       200      230

erf.most.zref   = 25.0

erf.most.rico.theta_z0 = 298.7
erf.most.rico.qsat_z0 = 0.021833

erf.rayleigh_damp_W = true
erf.rayleigh_damp_U = true
erf.rayleigh_damp_V = true
erf.rayleigh_damp_T = true
erf.rayleigh_dampcoef = 0.2
erf.rayleigh_zdamp = 2000.

erf.fixed_dt = 0.5
erf.fixed_fast_dt = 0.1

erf.check_int       = 20000

erf.plot_int_1      = 600
erf.plot_vars_1     = density rhotheta x_velocity y_velocity z_velocity pressure temp theta qt qp qv qc qsat qrain rain_accum qsnow qgraup qi

erf.dycore_horiz_adv_type    = Upwind_3rd
erf.dycore_vert_adv_type     = Upwind_3rd
erf.dryscal_horiz_adv_type   = Upwind_3rd
erf.dryscal_vert_adv_type    = Upwind_3rd
erf.moistscal_horiz_adv_type = Upwind_3rd
erf.moistscal_vert_adv_type  = Upwind_3rd

erf.buoyancy_type   = 2

super_droplets_moisture.initial_distribution_type = "uniform"
super_droplets_moisture.diagnostics_interval = -1
super_droplets_moisture.coalescence_kernel = "Halls"
super_droplets_moisture.aerosols = NH4HSO4
super_droplets_moisture.num_initializations = 2
super_droplets_moisture.density_scaling = true

super_droplets_moisture.0.initial_aerosol_distribution_type_NH4HSO4 = "radius_log_normal"
super_droplets_moisture.0.initial_aerosol_mean_radius_NH4HSO4 = 30.0e-9
super_droplets_moisture.0.initial_aerosol_geomstd_radius_NH4HSO4 = 1.28
super_droplets_moisture.0.initial_number_density = 9.0e7
super_droplets_moisture.0.initial_particles_per_cell = 64

super_droplets_moisture.1.initial_aerosol_distribution_type_NH4HSO4 = "radius_log_normal"
super_droplets_moisture.1.initial_aerosol_mean_radius_NH4HSO4 = 140.0e-9
super_droplets_moisture.1.initial_aerosol_geomstd_radius_NH4HSO4 = 1.75
super_droplets_moisture.1.initial_number_density = 1.5e7
super_droplets_moisture.1.initial_particles_per_cell = 64

erf.custom_forcing_uses_primitive_vars = false
