#!/bin/bash
#
# Generate ERF input files by merging a base template with override files
#
# Usage:
#   ./generate_inputs.sh [OPTIONS] OUTPUT_NAME OVERRIDE_FILE [OVERRIDE_FILE ...]
#
# Options:
#   --base=FILE       Base template file (default: templates/base.inputs)
#   --output-dir=DIR  Output directory (default: ../inputs)
#   --dry-run         Show merged output without writing
#   --list            List available templates and overrides
#   --help            Show this help message
#
# Examples:
#   ./generate_inputs.sh BF02_moist_bubble_SDM_custom sdm_nacl.conf my_custom.conf
#   ./generate_inputs.sh --base=templates/base.inputs my_case overrides/kessler.conf
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
DEFAULT_BASE="$ROOT_DIR/inputs/templates/base.inputs"
DEFAULT_OUTPUT_DIR="$ROOT_DIR/inputs"
OVERRIDE_DIR="$ROOT_DIR/inputs/templates/overrides"

# Colors
if [[ -t 1 ]]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' NC=''
fi

error() { echo -e "${RED}ERROR:${NC} $*" >&2; exit 1; }
info()  { echo -e "${GREEN}==>${NC} $*"; }

usage() {
    sed -n '/^# Usage:/,/^[^#]/p' "$0" | grep '^#' | sed 's/^# \?//'
    exit 0
}

list_templates() {
    echo "Base templates:"
    for f in "$ROOT_DIR/inputs/templates"/*.inputs; do
        [[ -f "$f" ]] && echo "  $(basename "$f")"
    done
    echo
    echo "Override files:"
    for f in "$OVERRIDE_DIR"/*.conf; do
        [[ -f "$f" ]] && echo "  $(basename "$f")"
    done
}

# Merge input files: later files override earlier ones
# For AMReX inputs format: key = value
merge_inputs() {
    local output_file="$1"
    shift
    local files=("$@")

    # Use associative array to track key-value pairs (preserves last value)
    declare -A params
    declare -a order  # Track order of keys for output

    for file in "${files[@]}"; do
        while IFS= read -r line; do
            # Skip empty lines and pure comments
            if [[ -z "${line// }" ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
                continue
            fi

            # Parse key = value (with optional inline comment)
            if [[ "$line" =~ ^[[:space:]]*([a-zA-Z0-9._]+)[[:space:]]*=[[:space:]]*(.*) ]]; then
                local key="${BASH_REMATCH[1]}"
                local value="${BASH_REMATCH[2]}"

                # Track key order (only add if new)
                if [[ -z "${params[$key]+isset}" ]]; then
                    order+=("$key")
                fi
                params["$key"]="$value"
            fi
        done < "$file"
    done

    # Generate output with section comments
    {
        echo "# ------------------  INPUTS TO MAIN PROGRAM  -------------------"
        echo "# Generated by generate_inputs.sh on $(date)"
        echo "# Base: $(basename "${files[0]}")"
        echo "# Overrides: ${files[*]:1}"
        echo "# ------------------------------------------------------------------"
        echo

        local prev_prefix=""
        for key in "${order[@]}"; do
            # Add section headers based on key prefix
            local prefix="${key%%.*}"
            if [[ "$prefix" != "$prev_prefix" ]]; then
                [[ -n "$prev_prefix" ]] && echo
                prev_prefix="$prefix"
            fi
            echo "${key} = ${params[$key]}"
        done
    } > "$output_file"
}

# Parse arguments
BASE_FILE="$DEFAULT_BASE"
OUTPUT_DIR="$DEFAULT_OUTPUT_DIR"
DRY_RUN=""
OUTPUT_NAME=""
OVERRIDE_FILES=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --base=*)       BASE_FILE="${1#*=}" ;;
        --output-dir=*) OUTPUT_DIR="${1#*=}" ;;
        --dry-run)      DRY_RUN=1 ;;
        --list)         list_templates; exit 0 ;;
        --help|-h)      usage ;;
        -*)             error "Unknown option: $1" ;;
        *)
            if [[ -z "$OUTPUT_NAME" ]]; then
                OUTPUT_NAME="$1"
            else
                OVERRIDE_FILES+=("$1")
            fi
            ;;
    esac
    shift
done

# Validate
[[ -z "$OUTPUT_NAME" ]] && error "Missing output name. Use --help for usage."
[[ ${#OVERRIDE_FILES[@]} -eq 0 ]] && error "At least one override file required."
[[ ! -f "$BASE_FILE" ]] && error "Base file not found: $BASE_FILE"

# Resolve override file paths
RESOLVED_OVERRIDES=()
for override in "${OVERRIDE_FILES[@]}"; do
    if [[ -f "$override" ]]; then
        RESOLVED_OVERRIDES+=("$override")
    elif [[ -f "$OVERRIDE_DIR/$override" ]]; then
        RESOLVED_OVERRIDES+=("$OVERRIDE_DIR/$override")
    else
        error "Override file not found: $override (looked in . and $OVERRIDE_DIR)"
    fi
done

# Prepare all input files
ALL_FILES=("$BASE_FILE" "${RESOLVED_OVERRIDES[@]}")

OUTPUT_FILE="$OUTPUT_DIR/inputs_${OUTPUT_NAME}"

if [[ -n "$DRY_RUN" ]]; then
    info "Would generate: $OUTPUT_FILE"
    info "Merging: ${ALL_FILES[*]}"
    echo
    echo "--- Preview ---"
    merge_inputs /dev/stdout "${ALL_FILES[@]}"
else
    info "Generating: $OUTPUT_FILE"
    merge_inputs "$OUTPUT_FILE" "${ALL_FILES[@]}"
    info "Done. Created $OUTPUT_FILE"
fi
