#!/bin/bash
#
# Run script for initial sampling case: radius_log_normal
# Platform: dane
# Generated by run_erf.sh on Thu Jan 29 16:22:24 PST 2026
#

set -e

# Configuration
NTASKS=4
NNODES=1
GPU_SUPPORT=false
GPUS_PER_TASK=1
EXEC=/g/g92/ghosh5/Codes/ERF-builds/dane/Exec/MoistRegTests/Bubble/erf_bubble
INPUT=inputs_radius_log_normal

echo "Running ERF for initial sampling (max_step = 0)"
echo "Case: radius_log_normal"
echo "Platform: dane"
echo "Tasks: $NTASKS"
echo "Nodes: $NNODES"
[[ "$GPU_SUPPORT" == "true" ]] && echo "GPUs per task: $GPUS_PER_TASK"
echo

# Determine how to launch MPI job based on scheduler
# SLURM-based system (using debug queue for interactive runs)
DEBUG_QUEUE=pdebug
if [[ "$GPU_SUPPORT" == "true" ]]; then
    # Total GPUs = ntasks * gpus_per_task
    TOTAL_GPUS=$(($NTASKS * $GPUS_PER_TASK))
    srun -n $NTASKS -N $NNODES -p $DEBUG_QUEUE -G $TOTAL_GPUS $EXEC $INPUT 2>&1 | tee output.log
else
    srun -n $NTASKS -N $NNODES -p $DEBUG_QUEUE $EXEC $INPUT 2>&1 | tee output.log
fi

echo
echo "Initial sampling complete. Check output files."
