# Case: mass_constant_sampled
# All particles have the same aerosol mass, with sampled multiplicity

super_droplets_moisture.multiplicity_type = "sampled"
super_droplets_moisture.initial_number_density = 1.0e9 #m^{-3}
super_droplets_moisture.initial_aerosol_distribution_type_NaCl = "mass_constant"
super_droplets_moisture.initial_aerosol_mean_mass_NaCl = 1.0e-19 #kg
