# Case: mass_exponential
# Exponential mass distribution

super_droplets_moisture.initial_aerosol_distribution_type_NaCl = "mass_exponential"
super_droplets_moisture.initial_aerosol_mean_mass_NaCl = 1.0e-19 #kg
super_droplets_moisture.initial_aerosol_min_mass_NaCl = 1.0e-22 #kg
super_droplets_moisture.initial_aerosol_max_mass_NaCl = 5.0e-19 #kg
