# Case: radius_log_normal
# Log-normal radius distribution with specified min/max bounds

super_droplets_moisture.initial_aerosol_distribution_type_NaCl = "radius_log_normal"
super_droplets_moisture.initial_aerosol_mean_radius_NaCl = 5.0e-8 #m (50 nm)
super_droplets_moisture.initial_aerosol_min_radius_NaCl = 1.0e-9 #m (1 nm)
super_droplets_moisture.initial_aerosol_max_radius_NaCl = 1.0e-6 #m (1 μm)
super_droplets_moisture.initial_aerosol_geomstd_radius_NaCl = 2.0
