# Case: radius_lognormal_autorange_sampled
# Log-normal radius distribution with automatic range determination and sampled multiplicity

super_droplets_moisture.multiplicity_type = "sampled"
super_droplets_moisture.initial_number_density = 1.0e9 #m^{-3}
super_droplets_moisture.initial_aerosol_distribution_type_NaCl = "radius_lognormal_autorange"
super_droplets_moisture.initial_aerosol_mean_radius_NaCl = 5.0e-8 #m (50 nm)
super_droplets_moisture.initial_aerosol_geomstd_radius_NaCl = 2.0
