# Override: Sampling options (last 4 lines)
# These parameters define the aerosol distribution and will vary between cases

super_droplets_moisture.initial_aerosol_distribution_type_NaCl = "mass_exponential"
super_droplets_moisture.initial_aerosol_mean_mass_NaCl = 1.0e-19 #kg
super_droplets_moisture.initial_aerosol_min_mass_NaCl = 1.0e-22 #kg
